# config/system.yaml
# Central system configuration for the Professional Algorithmic Trading Backtesting System
data:
  root: MASTER_DATASET
  pairs: [EUR_USD, GBP_USD, USD_JPY, AUD_USD, USD_CAD, NZD_USD, EUR_GBP, XAU_USD, GBP_JPY, EUR_JPY]
  timeframes: ["1m","5m","15m","30m","1h","4h","1d","1w"]
  extras: [economic_calendar, news_sentiment]
  # Golden rule validation
  min_completeness: 0.90
  max_critical_gaps: 2
  min_points: 1000
  fail_on_synthetic: true
costs:
  # session_profile should be derived from your dataset (e.g., LDN/NY/TYO sessions)
  spread_source: session_profile
  slippage_pips_base: [0.5, 1.0]   # market orders; a volatility scaler will apply during stress
  commission_per_lot_range: [0, 7]
  rollover_block_utc: ["21:55","22:10"]
  widen_spreads_during_news: true
hardware:
  cpu: "AMD 5950X (16c/32t)"
  parallel_workers: 30
validation:
  # Walk-Forward Analysis settings
  wfa:
    train_months: 6
    test_months: 3
    stride_months: 1
    enforce_monotonicity_tau_gt: 0.0
  # Monte Carlo stress testing
  mc:
    runs: 1000
    latency_ms_range: [2, 40]
    fill_drop_rate_range: [0.002, 0.01]
    cost_inflation_factor: 1.25  # +25% stress test
risk:
  target_ror_max: 0.01  # Risk-of-Ruin target <= 1%
selection:
  dd_max: 0.12
  min_trades_per_year: 50
  capacity_lot_limit: 1
  news_sensitivity_collapse_max: 0.25
  regime_concentration_max: 0.60  # no single quarter > 60% PnL
scoring:
  weights:
    sharpe_oos_deflated: 0.50
    esi: 0.20
    cagr: 0.15
    max_dd: -0.10
    cost_sensitivity: -0.05
reproducibility:
  record_data_checksums: true
  log_random_seeds: true
  persist_wfa_splits: true
  persist_mc_streams: true
scheduling:
  weekly_reoptimize_top_n: 3
  keep_weeks_history: 8
outputs:
  registry_path: "reports/experiment_registry.jsonl"
  topk_report_path: "reports/top_k_report.html"
  deployment_bundle_dir: "reports/deployment_bundles"
