assets: [
  "EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD", "NZDUSD",
  "EURJPY", "GBPJPY", "USDCHF", "XAUUSD"
]
# DXY feature only
---
# ===== FX + XAUUSD universe (with DXY as feature) =====
assets: [
  "EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD", "NZDUSD",
  "EURJPY", "GBPJPY", "USDCHF", "XAUUSD"
]
# DXY is used as a feature / regime overlay (not traded).
dxy:
  symbol_aliases: ["DXY", "DX-Y.NYB", "DX1!", "ICEUS:DX"]
  feature_only: true

# Timeframes used across all assets and DXY features.
# (DXY is resampled to match.)
timeframes: ["1h", "4h"]
resample_from_native: true  # If your raw CSVs are mixed timeframes

capital: 100000
risk_per_trade: [0.25, 0.5, 0.75, 1.0]  # percent of equity

# Pip sizes & quote precision (used for FX/XAU pip math, OCO, ATR in pips)
pip_precision:
  default: 0.0001
  JPY: 0.01       # USDJPY/EURJPY/GBPJPY
  XAUUSD: 0.1

# Estimated spreads/commission/slippage — adjust to your venue
costs:
  commission_bps:
    default: 0    # most FX is spread-only; set to nonzero if applicable
  spread_pips:    # conservative typical values; tune to your broker
    EURUSD: 0.8
    GBPUSD: 1.4
    USDJPY: 0.9
    AUDUSD: 1.0
    USDCAD: 1.2
    NZDUSD: 1.2
    EURJPY: 1.3
    GBPJPY: 1.9
    USDCHF: 1.3
    XAUUSD: 2.0   # in “pips” per pip_precision mapping
  slippage_bps:
    default: 2
    news_bump_bps: 5   # add during configured news windows

# Backtest rigor
backtest:
  timezone: "Europe/London"
  bar_close_execution: true         # signals execute on next bar open (or close→close)
  latency_ms_jitter: [50, 150]      # random latency within this range
  walk_forward:
    train_bars: [2000, 4000]
    test_bars: [500, 1000]
    kfold_purged: 5
  monte_carlo: 500
  stress:
    fee_multiplier: [1.0, 2.0]
    slip_multiplier: [1.0, 2.0]
    data_dropout_prob: 0.01         # occasional missing bars

# Economic news calendar integration (no look-ahead)
news:
  use_as_features: true
  as_trading_filter: true           # optional entry/exit blackout
  calendar_source: "data/news/calendar.csv"  # cached local file
  timezone: "Europe/London"
  fields_expected: [timestamp, title, currency, impact, forecast, previous, actual]
  release_latency_seconds: 5        # simulate parsing delay
  blackout_windows:                 # realistic pre/post event controls
    high:   {pre_minutes: 15, post_minutes: 5}
    medium: {pre_minutes: 10, post_minutes: 3}
    low:    {pre_minutes: 5,  post_minutes: 2}
  revisions_handling: "after_next_bar"  # revisions only affect t+1
  rate_limit:                        # for any fetching scripts you add
    max_calls_per_min: 30
    cache_path: "data/cache/news"
    backoff_seconds: [1, 2, 4, 8]
  mapping:                           # which currencies map to which symbols
    USD: [EURUSD, GBPUSD, USDJPY, AUDUSD, USDCAD, NZDUSD, USDCHF, XAUUSD]
    EUR: [EURUSD, EURJPY]
    GBP: [GBPUSD, GBPJPY]
    JPY: [USDJPY, EURJPY, GBPJPY]
    CAD: [USDCAD]
    AUD: [AUDUSD]
    NZD: [NZDUSD]

# DXY feature/overlay controls
features:
  dxy:
    enabled: true
    resample: "match_asset_tf"   # 1h & 4h to match price bars
    rolling_z_windows: [20, 60]
    correlation_window: 120
    risk_overlay:
      enabled: true               # reduce risk when DXY disagrees with pair bias
      scale_min: 0.5
      scale_max: 1.0

families:
  V3_TF:
    donchian: [20, 40, 60]
    ma_len: [50, 100, 200]
    atr_k_entry: [1.0, 1.5, 2.0]
    atr_k_trail: [1.5, 2.0, 3.0]
    scale_in_layers: [0, 1, 2, 3]
    scale_in_gap_atr: [0.8, 1.0, 1.2]
    partial_tp_r: [1.5, 2.0]
    partial_tp_frac: [0.33, 0.5]

  V3_MR:
    rsi_len: [7, 14]
    rsi_low_high: [[25, 75], [20, 80]]
    bb_len: [20]
    bb_dev: [2.0, 2.5, 3.0]
    mean_exit: ["midband", "sma"]
    max_layers: [0, 1, 2]

  V3_RS:
    adx_len: [14, 20]
    adx_thr: [18, 22, 25]
    vol_z_thr: [0.0, 0.5]
    hysteresis: [1, 2, 3]

risk:
  daily_loss_cap_pct: 2.0
  rolling3d_cap_pct: 4.0
  max_exposure_per_asset_pct: 20.0
  max_portfolio_exposure_pct: 80.0
  break_even_R: [0.7, 1.0]
  time_exit_bars: [48, 96]